### ISSUE TITLE
Integration with Eye Tracking Software

### ISSUE THREAD

**Issue by HackXIt** [HackXIt/assist-heidi-speech-jokey#4]
## Description
Develop and test the integration with eye-tracking software for cursor movement and selection. This should allow seamless navigation and interaction for users relying on eye-tracking technology.

### Sub-tasks
- [ ] Implement integration logic with eye-tracking software. _(this means making sure that cursor movement with existing eye tracking software works with the current UI)_
- [ ] Test cursor movement and selection accuracy. _(essential for usability)_
- [ ] Ensure compatibility with major eye-tracking software. _(i.e. what Natascha uses)_

## Estimations
- **Size:** Large
- **Priority:** High

## Branch Name
`feature/eye-tracking-integration`
